
// add employee data
export const CREATE_EMPLOYEE_DATA_START="CREATE_EMPLOYEE_DATA_START"
export const CREATE_EMPLOYEE_DATA_SUCCESS="CREATE_EMPLOYEE_DATA_SUCCESS"
export const CREATE_EMPLOYEE_DATA_ERROR="CREATE_EMPLOYEE_DATA_ERROR"

// get employee data
export const LOAD_EMPLOYEE_DATA_START="LOAD_EMPLOYEE_DATA_START"
export const LOAD_EMPLOYEE_DATA_SUCCESS="LOAD_EMPLOYEE_DATA_SUCCESS"
export const LOAD_EMPLOYEE_DATA_ERROR="LOAD_EMPLOYEE_DATA_ERROR"


// delete employee data
export const DELETE_EMPLOYEE_DATA_START="DELETE_EMPLOYEE_DATA_START"
export const DELETE_EMPLOYEE_DATA_SUCCESS="DELETE_EMPLOYEE_DATA_SUCCESS"
export const DELETE_EMPLOYEE_DATA_ERROR="DELETE_EMPLOYEE_DATA_ERROR"
// update employee data
export const UPDATE_EMPLOYEE_DATA_START="UPDATE_EMPLOYEE_DATA_START"
export const UPDATE_EMPLOYEE_DATA_SUCCESS="UPDATE_EMPLOYEE_DATA_SUCCESS"
export const UPDATE_EMPLOYEE_DATA_ERROR="UPDATE_EMPLOYEE_DATA_ERROR"